name: Boosters
main: com.mrfdev.boosters.Boosters
version: ${version}
api-version: '1.20'
author: mrfloris
website: https://github.com/mrfdev/Boosters
description: Persist and restore server-wide booster events (mcMMO xprate, Jobs Reborn boosts) across restarts.

softdepend:
  - mcMMO
  - Jobs
  - PlaceholderAPI

commands:
  rate:
    description: Shows current stored mcMMO xprate and Jobs boost restore status.
    usage: /rate
    permission: boosters.rate

permissions:
  boosters.rate:
    default: true
  boosters.admin:
    default: op
